///**
// * Created by macuser on 2/26/15.
// */
//{
//    "name":"ns1:timeSeriesResponseType",
//    "declaredType":"org.cuahsi.waterml.TimeSeriesResponseType",
//    "scope":"javax.xml.bind.JAXBElement$GlobalScope",
//    "value":{
//        "queryInfo":{
//            "creationTime":null,
//            "queryURL":"http://127.0.0.1:8080/nwis/iv/",
//            "criteria":{
//                "locationParam":"[ALL:13022500]",
//                "variableParam":"[00060, 00065]",
//                "timeParam":null,
//                "parameter":[],
//                "methodCalled":null
//        },"note":[{
//            "value":"[ALL:13022500]",
//            "type":null,
//            "href":null,
//            "title":"filter:sites",
//            "show":null
//        },{
//            "value":"[mode=LATEST, modifiedSince=null]",
//            "type":null,
//            "href":null,
//            "title":"filter:timeRange",
//            "show":null
//        },{
//            "value":"methodIds=[ALL]",
//            "type":null,
//            "href":null,
//            "title":"filter:methodId",
//            "show":null
//        },{
//            "value":"2015-02-26T17:45:28.315Z",
//            "type":null,
//            "href":null,
//            "title":"requestDT",
//            "show":null
//        },{
//            "value":"405cd5a0-bddf-11e4-a75e-6cae8b6642f6",
//            "type":null,
//            "href":null,
//            "title":"requestId",
//            "show":null
//        },{
//            "value":"Provisional data are subject to revision. Go to http://waterdata.usgs.gov/nwis/help/?provisional for more information.",
//            "type":null,
//            "href":null,
//            "title":"disclaimer",
//            "show":null
//        },{
//            "value":"caas01",
//            "type":null,
//            "href":null,
//            "title":"server",
//            "show":null
//        }],
//            "extension":null
//    },
//    "timeSeries":[{"sourceInfo":{
//        "siteName":"SNAKE RIVER AB RESERVOIR NR ALPINE WY",
//        "siteCode":[{
//            "value":"13022500",
//            "network":"NWIS",
//            "siteID":null,
//            "agencyCode":"USGS",
//            "agencyName":null,
//            "default":null
//        }],
//        "timeZoneInfo":{
//            "defaultTimeZone":{
//                "zoneOffset":"-07:00",
//                "zoneAbbreviation":"MST"
//            },"daylightSavingsTimeZone":{
//                "zoneOffset":"-06:00","zoneAbbreviation":"MDT"
//            },"siteUsesDaylightSavingsTime":true
//        },"geoLocation":{
//            "geogLocation":{
//                "srs":"EPSG:4326",
//                "latitude":43.1961111,
//                "longitude":-110.8894444
//            },"localSiteXY":[]
//        },"elevationM":null,
//        "verticalDatum":null,
//        "note":[],
//        "extension":null,
//        "altname":null,
//        "siteType":[],
//        "siteProperty":[{
//            "value":"ST",
//            "type":null,
//            "name":"siteTypeCd",
//            "uri":null
//        },{
//            "value":"17040103",
//            "type":null,
//            "name":"hucCd",
//            "uri":null
//        },{
//            "value":"56",
//            "type":null,
//            "name":"stateCd",
//            "uri":null
//        },{
//            "value":"56023",
//            "type":null,
//            "name":"countyCd",
//            "uri":null
//        }],"oid":null,
//        "metadataTime":null
//    },"variable":{
//        "variableCode":[{
//            "value":"00060",
//            "network":"NWIS",
//            "vocabulary":"NWIS:UnitValues",
//            "variableID":45807197,"default":true
//        }],"variableName":"Streamflow, ft&#179;/s",
//        "variableDescription":"Discharge, cubic feet per second",
//        "valueType":"Derived Value",
//        "dataType":null,
//        "generalCategory":null,
//        "sampleMedium":null,
//        "unit":{
//            "unitName":null,
//            "unitDescription":null,
//            "unitType":null,
//            "unitAbbreviation":"ft3/s",
//            "unitCode":null,
//            "unitID":null
//        },"options":{
//            "option":[{
//                "value":null,
//                "name":"Statistic",
//                "optionID":null,
//                "optionCode":"00011"
//            }]},
//        "note":[],
//        "related":null,
//        "extension":null,
//        "noDataValue":-999999.0,
//        "timeScale":null,
//        "speciation":null,
//        "categories":null,
//        "variableProperty":[],
//        "oid":"45807197",
//        "metadataTime":null},
//        "values":[{
//            "value":[{
//                "value":"1800",
//                "dateTimeAccuracyCd":null,
//                "qualifiers":["P"],
//                "censorCode":null,
//                "dateTime":"2015-02-26T10:30:00.000-07:00",
//                "timeOffset":null,
//                "dateTimeUTC":null,
//                "methodID":null,
//                "sourceID":null,
//                "accuracyStdDev":null,
//                "sampleID":null,
//                "methodCode":null,
//                "sourceCode":null,
//                "labSampleCode":null,
//                "offsetValue":null,
//                "offsetTypeID":null,
//                "offsetTypeCode":null,
//                "codedVocabulary":null,
//                "codedVocabularyTerm":null,
//                "qualityControlLevelCode":null,
//                "metadataTime": null,
//                "oid":null
//            }],
//            "units":null,
//            "qualifier":[{
//                "qualifierCode":"P",
//                "qualifierDescription":"Provisional data subject to revision.",
//                "qualifierID":0,
//                "network":"NWIS",
//                "vocabulary":"uv_rmk_cd",
//                "default":null
//            }],
//            "qualityControlLevel":[],
//            "method":[{
//                "methodCode":null,
//                "methodDescription":"",
//                "methodLink":null,
//                "methodID":2
//            }],
//            "source":[],
//            "offset":[],
//            "sample":[],
//            "censorCode":[]
//        }],"name":"USGS:13022500:00060:00011"
//    },{
//        "sourceInfo":{
//            "siteName":"SNAKE RIVER AB RESERVOIR NR ALPINE WY",
//            "siteCode":[{
//                "value":"13022500",
//                "network":"NWIS",
//                "siteID":null,
//                "agencyCode":"USGS",
//                "agencyName":null,
//                "default":null
//            }],"timeZoneInfo":{
//                "defaultTimeZone":{
//                    "zoneOffset":"-07:00",
//                    "zoneAbbreviation":"MST"
//                },"daylightSavingsTimeZone":{
//                    "zoneOffset":"-06:00",
//                    "zoneAbbreviation":"MDT"
//                },"siteUsesDaylightSavingsTime":true
//            },"geoLocation":{
//                "geogLocation":{
//                    "srs":"EPSG:4326",
//                    "latitude":43.1961111,
//                    "longitude":-110.8894444
//                },"localSiteXY":[]
//            },"elevationM":null,
//            "verticalDatum":null,
//            "note":[],
//            "extension":null,
//            "altname":null,
//            "siteType":[],
//            "siteProperty":[{
//                "value":"ST",
//                "type":null,
//                "name":"siteTypeCd",
//                "uri":null
//            },{
//                "value":"17040103",
//                "type":null,
//                "name":"hucCd",
//                "uri":null
//            },{
//                "value":"56",
//                "type":null,
//                "name":"stateCd",
//                "uri":null
//            },{
//                "value":"56023",
//                "type":null,
//                "name":"countyCd",
//                "uri":null
//            }],"oid":null,
//            "metadataTime":null
//        },"variable":{
//            "variableCode":[{
//                "value":"00065",
//                "network":"NWIS",
//                "vocabulary":"NWIS:UnitValues",
//                "variableID":45807202,
//                "default":true
//            }],
//            "variableName":"Gage height, ft",
//            "variableDescription":"Gage height, feet",
//            "valueType":"Derived Value",
//            "dataType":null,
//            "generalCategory":null,
//            "sampleMedium":null,
//            "unit":{
//                "unitName":null,
//                "unitDescription":null,
//                "unitType":null,
//                "unitAbbreviation":"ft",
//                "unitCode":null,
//                "unitID":null
//            },"options":{
//                "option":[{
//                    "value":null,
//                    "name":"Statistic",
//                    "optionID":null,
//                    "optionCode":"00011"
//                }]},"note":[],
//            "related":null,
//            "extension":null,
//            "noDataValue":-999999.0,
//            "timeScale":null,
//            "speciation":null,
//            "categories":null,
//            "variableProperty":[],
//            "oid":"45807202",
//            "metadataTime":null
//        },"values":[{
//            "value":[{
//                "value":"3.09",
//                "dateTimeAccuracyCd":null,
//                "qualifiers":["P"],
//                "censorCode":null,
//                "dateTime":"2015-02-26T10:30:00.000-07:00",
//                "timeOffset":null,
//                "dateTimeUTC":null,
//                "methodID":null,
//                "sourceID":null,
//                "accuracyStdDev":null,
//                "sampleID":null,
//                "methodCode":null,
//                "sourceCode":null,
//                "labSampleCode":null,
//                "offsetValue":null,
//                "offsetTypeID":null,
//                "offsetTypeCode":null,
//                "codedVocabulary":null,
//                "codedVocabularyTerm":null,
//                "qualityControlLevelCode":null,
//                "metadataTime":null,"oid":null}],
//            "units":null,
//            "qualifier":[{
//                "qualifierCode":"P",
//                "qualifierDescription":"Provisional data subject to revision.",
//                "qualifierID":0,
//                "network":"NWIS",
//                "vocabulary":"uv_rmk_cd",
//                "default":null
//            }],
//            "qualityControlLevel":[],
//            "method":[{
//                "methodCode":null,
//                "methodDescription":"",
//                "methodLink":null,
//                "methodID":3}],
//            "source":[],
//            "offset":[],
//            "sample":[],
//            "censorCode":[]
//        }],
//        "name":"USGS:13022500:00065:00011"
//    }]},
//    "nil":false,
//    "globalScope":true,
//    "typeSubstituted":false
//};